name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
    - title: '🚀 Features'
      labels:
          - 'feature'
    - title: '🐛 Bug Fixes'
      labels:
          - 'bugfix'
    - title: '🧰 Maintenance'
      label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-labels:
    - 'skip-changelog'
    - 'bump-manifest'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
    major:
        labels:
            - 'breaking'
    minor:
        labels:
            - 'feature'
    patch:
        labels:
            - 'fix'
template: |
    ## Changes

    $CHANGES
