name: Release Drafter

on:
    push:
        branches:
            - main
jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5
              id: draft
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - use: actions/checkout
            - name: Update plugin.manifest
              run: sed -i 's/version=[0-9\.]*/version=${{ steps.draft.outputs.tag_name }}/g' plugin.manifest
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Updated plugin version.
