name: Release Drafter

on:
    push:
        branches:
            - main
            - release/**
jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Draft Release
              uses: release-drafter/release-drafter@v5
              id: draft
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Update Plugin Version
              run: sed -i "s/version=[0-9\.]*/version=$(echo ${{ steps.draft.outputs.tag_name }} | sed 's/v//')/g" plugin.manifest
            - name: Create Update Version PR
              id: cpr
              uses: peter-evans/create-pull-request@v3
              with:
                  token: ${{ secrets.PAT }}
                  add-paths: plugin.manifest
                  branch: bump-manifest
                  branch-suffix: random
                  title: Bump manifest version to ${{ steps.draft.outputs.tag_name }}
                  body: Bump manifest version to ${{ steps.draft.outputs.tag_name }}
            - name: Enable Pull Request Automerge
              if: steps.cpr.outputs.pull-request-operation == 'created'
              uses: peter-evans/enable-pull-request-automerge@v1
              with:
                  token: ${{ secrets.PAT }}
                  pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
            - name: Auto approve
              if: steps.cpr.outputs.pull-request-operation == 'created'
              uses: juliangruber/approve-pull-request-action@v1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ steps.cpr.outputs.pull-request-number }}
