name: Start Release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Merge Main to Release
              uses: devmasx/merge-branch@v1.4.0
              with:
                  type: now
                  from_branch: main
                  target_branch: release
                  github_token: ${{ secrets.GITHUB_TOKEN }}
